# -*- coding: utf-8 -*-
"""IPL.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EO2Apn_DNE4EH8_oKgISlYcTdyP7RORC
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Sample IPL Data
data = {
    'season' : [2023, 2023, 2023, 2022, 2022, 2022, 2021, 2021, 2021],
    'team1': ['MI', 'CSK', 'RSB', 'MI', 'KKR', 'CSK', 'DC', 'RCB', 'MI'],
    'team2': ['CSK', 'RCB', 'MI', 'KKR', 'CSK', 'MI', 'MI', 'CSK', 'KKR'],
    'winner': ['CSK', 'CSK', 'MI', 'KKR', 'CSK', 'MI', 'DC', 'RCB', 'MI'],
    'venue': ['Mumbai', 'Chennai', 'Banglore', 'Mumbai', 'Kolkata', 'Chennai', 'Delhi', 'Hyderabad', 'Kolkata'],
    'player_of_match': ['Rohit Sharma', 'MS Dhoni', 'Virat Kohli', 'Jasprit Bumrah', 'Andre Russell', 'RAvindra Jadeja', 'Rishabh Pant', 'AB de Villiers', 'kieron Pollard'],
    'runs_scored': [160,180,200,175,165,150,185,190,150],
}
ipl_df = pd.DataFrame(data)

# 1. Basic Data Exploration
print(ipl_df.head())
print(ipl_df.info())

#2. Team Performance
team_wins = ipl_df['winner'].value_counts()
print("\nTeam wins:\n", team_wins)

#3. Player of the Match Anatysis
player_of_match_counts = ipl_df['player_of_match'].value_counts()
print("\nPlayer of the Match Analysis:\n", player_of_match_counts)

# 4. Runs Scored Analysis
average_runs_per_match = ipl_df['runs_scored'].mean() # Changed 'run_scored' to 'runs_scored'
print("\nAverage Runs Scored per match:", average_runs_per_match)

# 1. Bar Chart of Team Wins
plt.figure(figsize=(18, 6))
sns.countplot(x='winner', data=ipl_df)
plt.title('Number of Wins by Team')
plt.xlabel('Team')
plt.ylabel('Number of wins')
plt.show()

# 2.Histogram of Runs Scored
plt.figure(figsize=(8, 5))
plt.hist(ipl_df['runs_scored'],  bins=8)
plt.title(' Distribution of Runs Scored per Match')
plt.xlabel('Runs Scored')
plt.ylabel('Frequency')
plt.show()